server:
  port: 9001

redis:
  connection:
    host: 127.0.0.1
    port: 6379

spring:
  application:
    name: scene-mesh-mcp-server
  ai:
    mcp:
      server:
        name: sm-mcp-gateway
        version: 1.0.0
        type: SYNC
        instructions:
        sse-message-endpoint: /mcp/message
        sse-endpoint: /sse
        capabilities:
          tool: true
          resource: false
          prompt: false
          completion: false
        stdio: false
      # MCP Client
      client:
        type: SYNC
        request-timeout: 30s
        stdio:
          connections:
            bingcn:
              command: npx
              args: [
                "bing-cn-mcp"
              ]
        toolcallback:
          enabled: true

logging:
  level:
    root: INFO