spring:
  application:
    name: scene-mesh-manager
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/compute
    username: sm
    password: scene_mesh
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 60000
      keepalive-time: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

scene-mesh:
  # 基础设施配置
  infrastructure:
    redis:
      host: 192.168.31.91
      port: 6379
  ai:
    # 向量数据库
    vector:
      store:
        url: jdbc:postgresql://127.0.0.1:5432/compute
        username: sm
        password: scene_mesh
        driver: org.postgresql.Driver

server:
  port: 9001

logging:
  level:
    root: INFO
    com.scene.mesh: INFO
    org.hibernate: INFO
    org.springframework: INFO
    org.hibernate.SQL: INFO
