spring:
  application:
    name: scene-mesh-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: scene_mesh
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10          # ???????
      minimum-idle: 2               # ????????
      connection-timeout: 20000      # ????????
      idle-timeout: 300000          # ??????(5??)
      max-lifetime: 1200000         # ????????(20??)
      leak-detection-threshold: 60000 # ????????
      keepalive-time: 30000         # ??????
  jpa:
    hibernate:
      ddl-auto: update  # ?????update??????none/validate
    show-sql: true      # ?????SQL???????false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
logging:
  level:
    root: INFO
    com.scene.mesh: INFO
    org.hibernate: INFO
    org.springframework: INFO
    org.hibernate.SQL: INFO