scene-mesh:
  # 基础设施配置
  infrastructure:
    flink-web:
      host: 127.0.0.1
      port: 18081
    redis:
      host: 192.168.31.91
      port: 6379
    message:
      batch-size: 10
      timeout-seconds: 1
  # 主题配置
  topics:
    inbound-events: inbound_events
    matched-result: matched_result
    outbound-actions: outbound_actions
  # AI配置

  ai:
    mcp:
      server:
        url: http://192.168.31.91:9002
    # 向量数据库
    vector:
      store:
        url: jdbc:postgresql://192.168.31.91:5432/compute
        username: sm
        password: scene_mesh
        driver: org.postgresql.Driver
  # 消息类配置
  message-classes:
    event: com.scene.mesh.model.event.Event
    scene-matched-result: com.scene.mesh.engin.model.SceneMatchedResult
  # api client
  api-client:
    urls:
      product: http://192.168.31.91:3000/api/ee/services/objects/product?withReference=true
      llm: http://192.168.31.91:3000/api/ee/services/objects/intelligentModelProvider?withReference=true
      mcpserver: http://192.168.31.91:3000/api/ee/services/objects/mcpService?withReference=true
      knowledgeBase: http://192.168.31.91:3000/api/ee/services/objects/knowledgeBase?withReference=true